# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0002_report_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
