# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-29 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_label_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='users',
        ),
    ]
