# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_label_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=64),
        ),
    ]
