# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-30 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0006_auto_20180930_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='html',
        ),
    ]
