# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0007_remove_report_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
