# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 13:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('editor', '0009_auto_20181001_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='authors',
        ),
        migrations.AddField(
            model_name='report',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='report',
            name='archive',
        ),
        migrations.AddField(
            model_name='report',
            name='archive',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='editor.Archive'),
            preserve_default=False,
        ),
    ]
