# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0010_auto_20181001_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='archive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='editor.Archive'),
        ),
    ]
