# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_remove_label_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replied_by', to='editor.Comment'),
        ),
    ]
