# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0012_remove_label_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
