# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0013_auto_20181009_1700'),
        ('editor', '0014_manual_unique_label'),
    ]

    operations = [
    ]
