# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
#        ('editor', '0013_auto_20181008_2206'),
        ('editor', '0015_merge_20181009_1703'),
    ]

    operations = [
    ]
