# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-13 09:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actualname',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='actualname'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='organization'),
        ),
    ]
