# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180913_1703'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='location',
        ),
    ]
