# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-17 12:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180917_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.MaxLengthValidator(200)], verbose_name='location'),
        ),
    ]
