# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='reports',
            field=models.ManyToManyField(null=True, to='editor.Report'),
        ),
    ]
