# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-01 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20181001_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='reports',
            field=models.ManyToManyField(to='editor.Report'),
        ),
    ]
